name: PHP Linting

on:
  push:
    branches: [ main ]

  workflow_dispatch:

concurrency:
  group: "phplint"
  cancel-in-progress: true

jobs:
  phplint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint PHP
        uses: StephaneBour/actions-php-lint@8.2
